# Generated by Django 6.0.7 on 2026-07-12 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('license_category', models.CharField(max_length=10)),
                ('license_expiry_date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('name_model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('max_load_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle')),
            ],
        ),
    ]
