# Generated by Django 6.0.7 on 2026-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='safety_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
