# Generated by Django 6.0.7 on 2026-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
